doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_qlite'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            endurance: App\Type\EnduranceType
            progress: App\Type\ProgressType
            speed: App\Type\SpeedType
            strength: App\Type\StrengthType
            time: App\Type\TimeType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
